### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by Telesphoreo** [Adaptified/Utils#2]
`ant -f /Users/snip/NetBeansProjects/Utils-master -Dnb.internal.action.name=build jar
init:
Deleting: /Users/snip/NetBeansProjects/Utils-master/build/built-jar.properties
deps-jar:
Updating property file: /Users/snip/NetBeansProjects/Utils-master/build/built-jar.properties
Compiling 2 source files to /Users/snip/NetBeansProjects/Utils-master/build/classes
warning: [options] bootstrap class path not set in conjunction with -source 1.7
/Users/snip/NetBeansProjects/Utils-master/src/me/adaptified/utils/command/Command_unmute.java:36: error: cannot find symbol
        if (!plugin.MutedPlayers.contains(player)) {
  symbol:   variable MutedPlayers
  location: variable plugin of type T
  where T is a type-variable:
    T extends Plugin declared in class BukkitCommand
/Users/snip/NetBeansProjects/Utils-master/src/me/adaptified/utils/command/Command_unmute.java:41: error: cannot find symbol
        if (plugin.MutedPlayers.contains(player)) {
  symbol:   variable MutedPlayers
  location: variable plugin of type T
  where T is a type-variable:
    T extends Plugin declared in class BukkitCommand
/Users/snip/NetBeansProjects/Utils-master/src/me/adaptified/utils/command/Command_unmute.java:46: error: cannot find symbol
            plugin.MutedPlayers.remove(player);
  symbol:   variable MutedPlayers
  location: variable plugin of type T
  where T is a type-variable:
    T extends Plugin declared in class BukkitCommand
/Users/snip/NetBeansProjects/Utils-master/src/me/adaptified/utils/command/Command_unmute.java:47: error: cannot find symbol
            plugin.MutedPlayers.save();
  symbol:   variable MutedPlayers
  location: variable plugin of type T
  where T is a type-variable:
    T extends Plugin declared in class BukkitCommand
4 errors
/Users/snip/NetBeansProjects/Utils-master/nbproject/build-impl.xml:923: The following error occurred while executing this line:
/Users/snip/NetBeansProjects/Utils-master/nbproject/build-impl.xml:263: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 0 seconds)`

![screenshot 2016-03-09 20 17 05](https://cloud.githubusercontent.com/assets/7285557/13659210/ea9df012-e633-11e5-8a5b-9eb8902e3225.png)

**Comment by mgejay** [comment]
I will be reposting this git, please refrain from making similar issues! Thanks though!

**Comment by Telesphoreo** [comment]
k

**Comment by mgejay** [comment]
Closed in Utils Remastered commit.
